name: browser_launcher
description: A package that provides a standardized way to launch web browsers.

version: 0.1.1-dev

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/browser_launcher

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.6.2
  webkit_inspection_protocol: ^0.4.0

dev_dependencies:
  pedantic: ^1.5.0
  test: ^1.0.0
