name: browser_launcher
version: 1.1.2-wip
description: Provides a standardized way to launch web browsers for testing and tools.
repository: https://github.com/dart-lang/browser_launcher

environment:
  sdk: ^3.4.0

dependencies:
  logging: ^1.0.0
  path: ^1.8.0
  webkit_inspection_protocol: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.17.3
