name: browser_launcher
description: A standardized way to launch web browsers.

version: 0.0.1

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/browser_launcher

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:

