name: browser_launcher
version: 1.1.2-dev
description: Provides a standardized way to launch web browsers for testing and tools.
repository: https://github.com/dart-lang/browser_launcher

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.0
  webkit_inspection_protocol: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.3
