name: Dart

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:beta

    steps:
      - uses: actions/checkout@v2

      - name: dart pub get
        run: dart pub get

      - name: dart format
        run: dart format --output=none --set-exit-if-changed .

      - name: dart analyze
        run: dart analyze --fatal-infos

      - name: install chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install google-chrome-stable

      - name: dart test
        run: dart test
