name: Dart

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github
  DISPLAY: ':99'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [3.0, dev]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart pub get
        id: install

      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos

      - name: Run Xvfb 
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - run: dart test
